### ISSUE TITLE
Use of colours

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#10]
A while back, Meren and Didzis asked for examples of **use of colour** (I think it was you but Connections won't let me see or reply to the discussion). Anyway, thank you for this question - it made us focus on this for a bit! Always good! We have now added some examples on Design Library. The examples are mostly from public pages, but hopefully it can inspire you somewhat:

http://designlibrary.sebank.se/visual-identity/colours/#examples

/Ulrika, Ola, Jessi

**Comment by hjalmers** [comment]
My only input is that we should be a bit restrictive and think about when we're using colors and why. I get that they light things up a bit, especially if you want to highlight an offer or something on a public website and back in the days when I worked as a web editor we used them extensively to make things stick out. However in the context of an app or for the sake of clarity it often gets confusing. Why are we showing bond information on yellow, pension on purple, and savings on red in the above examples? And at the same time we have https://designlibrary.sebgroup.com/components/alert-ribbon/ and "alert" were purple is used for information, yellow for warnings and red for errors?

I think it works if you look at those examples separately, but if you add both an offer with red background to a page which also contains an error with red background what happens then?

**Comment by splashdust** [comment]
I agree that it would make sense to differentiate between applications and presentational websites when it comes to color usage.

In a presentational website, colors are used to direct attention to important content and to create contrast between different sections on the page and so on, whereas in an application colors are an important accessibility tool.

So in that sense, the public web concept sketches are maybe not very representative. They are a good example of how to use colors for a nice looking website, but I think we should compliment with examples of how to use colors correctly in an application.

@ulde01 @hjalmers
