### ISSUE TITLE
Success / confirmation checkbox

### ISSUE THREAD

**Issue by henrikhoglundseb** [sebgroup/design-library#100]
We use Success / confirmation checkboxes alot at SEB. I would like to choose one type off checkboxes to use everywhere. 

Ive made a design with the pictogram check and a round circle in dark-green-1. I would like to see other examples. I can make one outlined and "negavtive" version aswell. 

I know that Daniel Victorin has made a very nice version with a small animation. 

<img width="421" alt="Screenshot 2019-12-20 at 14 11 07" src="https://user-images.githubusercontent.com/46597007/71256951-a44bf600-2332-11ea-838f-74b33594bc53.png">
<img width="645" alt="Screenshot 2019-12-20 at 14 11 25" src="https://user-images.githubusercontent.com/46597007/71256952-a44bf600-2332-11ea-8000-6afc075c94a2.png">

**Comment by conandx** [comment]
![check-confirm](https://user-images.githubusercontent.com/44571006/72974779-e653d600-3dcf-11ea-9959-b4d357ad61e2.gif)

**Comment by henrikhoglundseb** [comment]
Så beautiful!

Skickat från min iPhone

23 jan. 2020 kl. 11:03 skrev Conny Andersson <notifications@github.com>:

﻿

[check-confirm]<https://user-images.githubusercontent.com/44571006/72974779-e653d600-3dcf-11ea-9959-b4d357ad61e2.gif>

**Comment by hjalmers** [comment]
Is the animated version available as a svg as well or just a gif?

**Comment by conandx** [comment]
this was just an example i found on the beautiful Internet.... as input to what would be lovely :grinning:

So - right now we don't have anything.... neither gif or svg  :hankey:

**Comment by axelgarciahenriksson** [comment]
Lovely! Great Find! I’m longing to see the SEB version of this at the end of a flow soon.

Nitpicky thoughts:

  *   Outlined version would be nice complement for those sober implementations.
  *   Small version for putting in to-do-lists etc
  *   Animation synced with loader etc - do we have an ‘SEB animation’ (thinking about speed, how the bounce should be timed, whether we start on zero degrees as this example or at another angle, clock-wise vs counter-clockwise and all other things I cannot think of)?

**Comment by danielvictorin** [comment]
![animation-icon-fill-v2](https://user-images.githubusercontent.com/46556775/76770225-dd62fd80-679d-11ea-9491-756b0beedd0a.gif)

For Your Meeting I created this spinner, but unfortunately never got developed..
It's divided into two sub-processes:
1. It is just spinning when loading
2. When successful it will chase it's own tail and the checkmark will pop

After discussions with @henrikhoglundseb we think that this can be a pretty neat last mile experience.
Though we need to co-create with a developer to find the correct timings, colors, icon and further explore the animated solution from a tech perspective.

**Comment by ulde01** [comment]
This loader has been added to design library. Feel free to build it!
