### ISSUE TITLE
Adjust Slide-out in Sketch

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#106]
### Changes
- 2 new alternative headers (with multiple headers and navigation)
- close-X is now dark grey
- Desktop uses 2 rem as paddings. Mobile uses 1 rem as padding
- Added 1 rem extra on top in mobile to not clash with mobile features

### Reason
Based on learnings and feedback from the original sketches.

![image](https://user-images.githubusercontent.com/45568194/73380206-e9fdc600-42c3-11ea-8989-54e924ba83b0.png)

### Details
See full description here:
https://designlibrary.sebgroup.com/patterns/modals/slide-out/#guidelines

**Comment by conandx** [comment]
**Changes:**
- 2 new alternative headers (with multiple headers and navigation)
- close-X is now dark grey
- Desktop uses 2REM as paddings. Mobile uses 1REM as padding
- Added 1 rem extra on top in mobile to not clash with mobile features

**Comment by ulde01** [comment]
I am unsure if this is news to our framework. This might be how it is today, but to make sure, I will treat it as a change. Thanks Conny!

**Comment by Kristina77** [comment]
What are the guidelines for the width of Slide out in all view ports? 

I have used 40% of the total area in desktop mode for Slide out, is that too wide?

**Comment by hjalmers** [comment]
Our bootstrap theme has two flavors for the slide-out modal. One which is fixed to 320 px and another one that gets the size from the content inside it (min width 320px and max width 768px). They don’t use a specific percentage of the screen width, the main reason for that being that the shells use these modal for presenting micro frontends inside iframes. It’s a bit complex and hard to explain but if they would use a percentage width it would be really hard to predict the responsive breakpoints for the content inside the modal. Ie. let’s assume the screen width is 1200 px, 40% of that would be 480 px. The content inside the iframe behaves like the screen width is 480px when it’s in fact 1200px if we resize the window to 1024px the modal would be 409,6px. 409,6 px and 480 px still fall under the same breakpoint range we have for our grid so there wouldn’t be a big issue in this case, but for other resolutions the case might be different and it would be hard to predict the behavior. Personally I think we would benefit from having more strict rules for the width of the modals (like the ones we have in the bootstrap implementation).

**Comment by Kristina77** [comment]
What flavor of Slide out do we use in Business Arena? I work with Digital signing right now and we are depending of Business Arenas Slide out.

 I also think we would benefit from having more strict rules for the width of the modals.

**Comment by hjalmers** [comment]
Business Arena uses the bootstrap theme for the modals but we haven’t added support for the larger version yet. But I’ll add it to our backlog:)

**Comment by Kristina77** [comment]
Thanks Robert!

**Comment by ulde01** [comment]
This component is updated. Only missing an example in Sketch (Malin).

**Comment by ulde01** [comment]
I am closing this now, it's been to long. Feel free to reopen the issue if needed.
