### ISSUE TITLE
Change name of the third button in Sketch to Button link (not Alternative button)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#107]
### Change
The button **Button link** used to be called Alternative button.
![image](https://user-images.githubusercontent.com/45568194/73255582-abcbae00-41c0-11ea-847c-77eba28105a8.png)
### Reason
The name Button link says what it is.

Feel free to update this in your frameworks so that we use the same language on components.

/Ulrika,
Design Management team

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/182
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/213
- [x] Angular https://github.com/sebgroup/ng-components/issues/82
- [ ] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/89
- [x] React https://github.com/sebgroup/react-components/issues/110

**Comment by ulde01** [comment]
Henrik changes this in Sketch

**Comment by henrikhoglundseb** [comment]
Party 🥳

Skickat från min iPhone

24 jan. 2020 kl. 11:02 skrev Ulrika <notifications@github.com>:

﻿

Henrik changes this in Sketch
