### ISSUE TITLE
Chips (new component)

### ISSUE THREAD

**Issue by JessiNygrenWalhed** [sebgroup/design-library#11]
### Design update 2020-01-13

**What is this?**
A new component to display a filter
![image](https://user-images.githubusercontent.com/45568194/72283192-8d9d7400-363e-11ea-9143-eea0e70337c3.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/chips/#specification

**Component identifier**
component-chip

**Follow up on development:**
- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/172
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/199
- [x] Angular https://github.com/sebgroup/ng-components/issues/72
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/86
- [x] React https://github.com/sebgroup/react-components/issues/102

Thank you!
/Ulrika

 **Original post from Jessi:**
Hey team!
I am adding the Tag/Label/Category component to the Design Library. Not as easy as I thought. This component can be used in some different ways and places. Sometimes it needs to be clickable, sometimes not. Sometimes in the context of a filter choice, sometimes as article labels, in tables and so on... So we need more than one component for it. 

I need to understand some of the contexts for it to be able to make the designs.
**How do you use it? It would really help me if you can give me some examples.** 

/Jessi

**Comment by mzemlickis** [comment]
These could be used in internet bank to filter transactions. I will poke Didzis to take a look at this. :)

**Comment by JessiNygrenWalhed** [comment]
Do you have any examples to show me, where you have used categories?

> These could be used in internet bank to filter transactions. I will poke Didzis to take a look at this. :)

**Comment by SusannaCh** [comment]
We are using labels in Alison for filtering (very similar to how SEB intranet are using them). We have a filter function where the user selects (click) the filter-label to see the result in the list below.

![image](https://user-images.githubusercontent.com/45751449/50961872-2730c380-14c9-11e9-9b3b-6814cca3bc42.png)

HandlaSjälv are also using filters for the fundlist. The user selects a filter choice in the lefthand "menu" and the choosen filter is shown above the list and can then be removed (disapears from the top of the list). Johan and Petra will know more about the plan for them.

![image](https://user-images.githubusercontent.com/45751449/50961986-7d9e0200-14c9-11e9-86df-e33eac28be0b.png)

**Comment by hjalmers** [comment]
Hi!

**Comment by axelgarciahenriksson** [comment]
In my humble opinion, they look too similar to buttons. Have you tried another shape, like pills or something?

**Comment by didzisspruds** [comment]
Sharing one example from Baltic Developer portal. The tabs / labels are used in two different cases - in one case as a label and in secon - as a button.

**Comment by JessiNygrenWalhed** [comment]
> Sharing one example from Baltic Developer portal. The tabs / labels are used in two different cases - in one case as a label and in secon - as a button.
> ![tag-label-example](https://user-images.githubusercontent.com/45620670/51038102-e74a0900-15ba-11e9-83e4-bc976cc7f72e.png)

Not sure what you mean by the Get-button. 😄

/Jessi

**Comment by didzisspruds** [comment]
@Jessi, "GET" is not used as a button but as a label. Only the gray ones (marked in screenshot) functions as buttons.
You can see live example here: https://developer.baltics.sebgroup.com/ob/apis/PAYMENTS

**Comment by JessiNygrenWalhed** [comment]
> @jessi, "GET" is not used as a button but as a label. Only the gray ones (marked in screenshot) functions as buttons.
> You can see live example here: https://developer.baltics.sebgroup.com/ob/apis/PAYMENTS

Ah! Got it. So ok, how many labels are there? And all categorised in colors? 
Why capitals on the label? 
The pills - the blue one is clickable, and the grey disabled?

**Comment by JessiNygrenWalhed** [comment]
> There are three types of requests: POST, GET, DELETE. All three are in caps as that's a common pattern for developers to use CAPS for these. All three is having different colors.
> All pills are clickable - it's gray by default; blue with white text on mouse over and dark gray when active.

The pills here, feels like they should be like toggle buttons instead? Or tabs? 
These are not categories? Right?

**Comment by didzisspruds** [comment]
No, pills are not categories. Yes, might be that toggle buttons could be better choice there. In the so called "old design system" we didn't have anything better, I guess.

**Comment by conandx** [comment]
Latest:
Chips - use when showing filtering options, with the possibility to remove (x)
Badge - use for showing a tag/category/status and highlight it from surrounding content.  (content still needed)
