### ISSUE TITLE
Shadow on card component (update)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#112]
### Design decision 2020-03-24
![image](https://user-images.githubusercontent.com/45568194/77452007-b63baa00-6df5-11ea-9aee-e0c47f902c2f.png)

**Change**
- Drop shadow height: 0.375 rem (used to be 0.125 rem)
- Drop shadow colour: Black (used to be Grey 2)

Also, note that the drop shadow is located 0.375 rem below the card and is not included in the actual card height

**Details**
https://designlibrary.sebgroup.com/components/card/#specification

**Reasoning**
There are too many variations because the design has been unspecified. The goal is to align the design of all our components and frameworks. 

If this issue is not relevant to you, please comment and close it.

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/197
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/277
- [x] Angular https://github.com/sebgroup/ng-components/issues/131
- [ ] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/95
- [x] React https://github.com/sebgroup/react-components/issues/180
- [x] Delorean https://github.sebank.se/delorean/portfolio-overview/issues/190

Thank you! :)
/Ulrika

**Comment by ulde01** [comment]
![image](https://user-images.githubusercontent.com/45568194/77174115-d818f200-6ac0-11ea-8c07-ecf37a69d3dc.png)

**Comment by ghost** [comment]
DeLorean have implemented this and are waiting for the code freeze to end.
