### ISSUE TITLE
Information next to input field

### ISSUE THREAD

**Issue by engslattfrida** [sebgroup/design-library#114]
Hi, 

I was at CX-coachning this wednesday and we discussed how and where to add information connected to an input field in a form. 

In this case, the user is adding a manual payment. When the user enter the amount, we want to show the amount translated into their base currency and also which FX-rate we calculated the EUR amount on. 

The same goes for when the user choose a date in the date picker, we want to show the cut-off time and the Credit value date for the payment, based on the date the user entered.

I have made one example, and would like some feedback regarding how we want to add information connected to an input field.

Thank you! 

<img width="611" alt="Information input field" src="https://user-images.githubusercontent.com/55842927/78895360-fabe7b00-7a6e-11ea-8d7f-69ac90319c38.PNG">

**Comment by conandx** [comment]
I think that's a reasonable solution to add a status next to a field.
Component-wise it looks suspiciously like a badge: 
![image](https://user-images.githubusercontent.com/44571006/79442309-aec48680-7fd8-11ea-8769-ede9e289c97a.png)
https://designlibrary.sebgroup.com/patterns/feedback-to-the-user/guide-the-user/badge/

**Comment by ghost** [comment]
Would it be enough to only show it in text. Without the grey background? Maybe ad an info icon instead? When the user fill in the input field this is something that will show when that is done, right? So maybe this will be clear without a background?

**Comment by TheresaHedlund** [comment]
Yes, agree with Jessi. Maybe it could be shown in the same place as the validation text. But black instead of red.

**Comment by engslattfrida** [comment]
Okey, I like the idea with info icon and then take away the gray background. I will try that! :) Thank you!

**Comment by ulde01** [comment]
I am closing this discussion as it is solved. Thank you!
