### ISSUE TITLE
New button variation: Sell-button

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#116]
### Design decision 2020-04-16
![image](https://user-images.githubusercontent.com/45568194/79326002-6c387680-7f12-11ea-88a6-0744a337d6f4.png)

**What is this**
A new Sell-button:
- Sell: The red button is new - see below for spec. The red colour (#D83C3C) is different to the red Delete-button ($seb-red).
- Buy: The blue button is a primary button - no change

**Specification for Sell-button**
- Default: #D83C3C
- Hover: #C32727
- Pressed: #C32727
- Focus box-shadow: 0 0 4px 1px #F03529 ;

The measurements are the same as the primary button. Note that the colours have no gradiant for desktop and hybrid. There is an exception made for mobile native buttons.
 
**Reason** 
To support user selection of buying and selling, the buttons have different colours. This button-pattern will be updated through the organisation and cross-plattforms. 
 
Have a look at the right column:
![image](https://user-images.githubusercontent.com/45568194/85410215-1b26ad80-b567-11ea-9eb1-f7f78a9ae3b7.png)

**Follow-up**
- [x] Vanilla: https://github.com/sebgroup/vanilla-pattern-library/issues/215
- [x] Bootstrap: https://github.com/sebgroup/bootstrap/issues/392
- [x] Angular: https://github.com/sebgroup/ng-components/issues/341
- [ ] AngularMaterial: https://github.com/sebgroup/seb-angular-material/issues/107
- [x] React: https://github.com/sebgroup/react-components/issues/428

Thank you! :)
/Ulrika

**Comment by ulde01** [comment]
Design decision 2020-04-16
image

What is this
A new Sell-button.

Sell: The red button is new #D83C3C. It is different to the red Delete-button.
Buy: The blue is a primary button, no change
Note that the colours have no gradiant for desktop and hybrid. There is an exception made for mobile native buttons.

Reason
To support user selection of buying and selling, the buttons have different colours. This button-pattern will be updated through the organisation and cross-plattforms.

- Need image with all the states (specification with colour codes) before this can be added to Design Library and communicated to the repositories
/Ulrika

**Comment by EldRoos** [comment]
sell focus:
box-shadow: 0 0 4px 1px #D83C3C

**Comment by kjocevicius** [comment]
Are the new colors available in vanilla as variables?
