### ISSUE TITLE
Toggle selector (mobile and desktop)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#14]
**Design change 2019-03-13**

The design update on Toggle selector was reviewed March 13:

**Change**
- Updated name: from Toggle button to Toggle selector
- Updated identifier: component-toggleselector
- Updated description of use
- Updated size and colours

See the details in the description: https://designlibrary.sebgroup.com/components/toggle-selector/

**Reason**
Analytics showed that the component was overlooked by users. It was unclear that the component was clickable.  

![image](https://user-images.githubusercontent.com/45568194/54550147-c1baf080-49ab-11e9-99bf-643cb12c82e0.png)

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/33
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/106
- [x] React https://github.sebank.se/DesignLibrary/ReactComponents/issues/50
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/11

**Comment by hjalmers** [comment]
@ulde01 what kind of toggle buttons are we talking about here? Isn't enough with slide toggles and checkboxes to toggle on or off state for things? See for example: https://sebgroup.github.io/bootstrap/checkboxes-and-slide-toggles

**Comment by JessiNygrenWalhed** [comment]
@hjalmers Isn’t that a toggle switch? 😍 
Will show you which component in DL is called toggle button. Tomorrow!

**Comment by hjalmers** [comment]
@JessiNygrenWalhed indeed it is:) I guess you're thinking about [this](https://ng-bootstrap.github.io/#/components/buttons/examples) kind of component that we're using on the login app [here](https://id.seb.se/ccs/digipass/xid) to switch between `user id` and `personal identity number` but with an icon/pictogram and space between the buttons? Basically it's just buttons mimicking the behaviour of regular checkboxes or radio buttons but in reality they provide the same functionality. I'm just afraid that we're making it harder for consumers and end users of design library by adding too many options that basically solve the same problem.

The large toggle button with an icon/pictogram is interesting though, I think it should resemble "normal" toggle buttons as much as possible to avoid confusion, but also with the current design and how we're using it, I think it should be avoided in applications and workflows as it's better suited for public websites and funnel flows.

In addition to standard checkboxes and radio buttons we're also using selects (dropdowns) and multi selects. Maybe it would be good to define something like the list below (just an example) that's not based on the component but on the problem they try to solve.

### User problems (just an example)

**Select/choose one option in a list of many**

| Component | Examples | Recommended usage |
|:------------|:---------|:-------------------|
|Radio buttons| <ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/radio-button/#usage)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/radio-buttons)</li></ul>| <ul><li>When available option are between 3-7 (?)</li><li>Avoid horizontal layout</li></ul>|
|Select (dropdown)|<ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/dropdown/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/dropdowns)</li></ul>|<ul><li>When more than 3 options (?)</li><li>Good for grouped/category options</li><li>Works well with typeahead</li><li>Avoid using long texts for options</li></ul>|
|Toggle buttons |<ul><li>[design library](https://designlibrary.sebgroup.com/components/toggle-button/)</li><li>[ng-bootstrap](https://ng-bootstrap.github.io/#/components/buttons/examples)</li></ul>|<ul><li>When available option are between 2-3 (?)</li><li>When using pictograms</li></ul>|
|Tabs |<ul><li>[design library](https://designlibrary.sebgroup.com/components/tab/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/tabs)</li></ul>|<ul><li>When available option are between 2-5 (?)</li><li>When involving navigation i.e url changes depending on selected option</li></ul>|

**Select/choose multiple options in a list o many**

| Component | Examples | Recommended usage |
|:------------|:---------|:-------------------|
|Checkboxes|<ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/checkbox/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/checkboxes-and-slide-toggles)</li></ul>|<ul><li>When available option are between 1-7 (?)</li><li>Avoid horizontal layout</li></ul>|
|Multi-select (dropdown)|<ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/dropdown/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/dropdowns)</li></ul>|<ul><li>When more than 5 options  (?)</li><li>Good for grouped/category options</li><li>Avoid using long texts for options</li></ul>|
|Toggle buttons |<ul><li>[design library](https://designlibrary.sebgroup.com/components/toggle-button/)</li><li>[ng-bootstrap](https://ng-bootstrap.github.io/#/components/buttons/examples)</li></ul>|<ul><li>When available option are between 2-3 (?)</li><li>When using pictograms</li></ul>|
|Slide toggles |<ul><li>[design library](https://designlibrary.sebgroup.com/components/toggle-switch/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/checkboxes-and-slide-toggles)</li></ul>|<ul><li>When available option are between 1-7 (?)</li><li>Avoid horizontal layout</li><li>To highlight on or off</li></ul>|

**Toggle state for one question/problem such as on/off, yes/no, true/false etc.**

| Component | Examples | Recommended usage |
|:------------|:---------|:-------------------|
|Checkboxes|<ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/checkbox/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/checkboxes-and-slide-toggles)</li></ul>|<ul><li>When text is long</li><li>When each state doesn't require additional explanation/clarification</li></ul>|
|Radio buttons|<ul><li>[design library](https://designlibrary.sebgroup.com/components/forms/radio-button/#usage)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/radio-buttons)</li></ul>| <ul><li>When text is long</li><li>When each state requires additional explanation/clarification</li><li>Avoid horizontal layout</li></ul>|
|Slide toggles |<ul><li>[design library](https://designlibrary.sebgroup.com/components/toggle-switch/)</li><li>[bootstrap](https://sebgroup.github.io/bootstrap/checkboxes-and-slide-toggles)</li></ul>|<ul><li>For simple options</li><li>Mobile and tablet layouts</li><li>To highlight on or off</li></ul>|
|Toggle buttons |<ul><li>[design library](https://designlibrary.sebgroup.com/components/toggle-button/)</li><li>[ng-bootstrap](https://ng-bootstrap.github.io/#/components/buttons/examples)</li></ul>|<ul><li>Should be avoided (?)</li></ul>|

**Comment by JessiNygrenWalhed** [comment]
So, some information to take in... 😍
But yes. We are talking about the toggle button with the icons. I´m not sure we should call it a toggle button though. For me, the tabs and the segmented control are sort of the same thing, this is (toggle button that we call it now) a more visual way of showing a radio button. And is part of a flow. And I think it fits perfectly in any sort of context if it's making it easier for the user to make a choice by adding an icon to the button.  The screenshot is from a sketch file Henrik made, toggle buttons for mobile. Maybe we can talk about this in Swedish when we find the time (sorry about that suggestion for you guys who need the english..😘), it would be easier to sort some things out before we take the discussion further here. I really think we are saying sort of the same thing? 🙃

![screenshot 2019-01-22 at 09 07 57](https://user-images.githubusercontent.com/45595414/51521912-4401bb00-1e28-11e9-8429-45f83b8f01c4.png)

**Comment by conandx** [comment]
We’ve also used the component in Morning in the context of changing expence category for a transaction.
[cid:image001.png@01D4B238.D7755290]
Note that this is axure-sketch, so not exactly pixel perfect ☺

.

**Comment by conandx** [comment]
and.... Looks like you can't email images...
![image](https://user-images.githubusercontent.com/44571006/51523544-38b08e80-1e2c-11e9-9f32-1992360c3177.png)

**Comment by ulde01** [comment]
**Design change 2019-03-13**

Updated on the Toggle selector was reviewed March 13: 

**Change**
- Updated name: from Toggle button to Toggle selector
- Updated description of use
- Updated size and colours

See the details in the description: https://designlibrary.sebgroup.com/components/upcoming/toggle-selector/

**Reason**
Analytics showed that the component was overlooked by users. It was unclear that the component was clickable.  

![image](https://user-images.githubusercontent.com/45568194/54550147-c1baf080-49ab-11e9-99bf-643cb12c82e0.png)

/Ulrika,
Design Management

**Comment by ulde01** [comment]
I am closing this issue for React because nothing has happened with it. I assume that it's not relevant. No hard feelings! ;) /Ulrika
