### ISSUE TITLE
Sticky bar

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#15]
A mobile/desktop component. Placed at the top of the screen. Scroll down for more images.
The sticky bar is a new component in Design library. It can be used both on mobile and desktop. There are two versions, depending on placement and content. Go to the styles tab in Design library for detailed descriptions.

**1. Sticky summary bar**

* Gives the user an overview, related to the choices made in the main content
* Height: 90 px
* Placement: At the top
* Identifier: component-stickysummarybar
* Specification: http://designlibrary.sebgroup.com/components/sticky-bar/sticky-summary-bar/#styles

**2. Sticky button bar**

* Gives the user the fasted possible call-to-action
* Height: 76 px
* Placement: At the bottom
* Identifier: component-stickybuttonbar
* Specification: http://designlibrary.sebgroup.com/components/sticky-bar/sticky-button-bar/#styles

Thank you,
Ulrika
Design management

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/8
- [x] SEB Bootstrap https://github.com/sebgroup/bootstrap/issues/104

**Comment by ulde01** [comment]
The design was reviewed 2019-01-17 and the team said YES to the design. Now Henrik (whom I can't @) 

- Will create descriptions

- Talk to his team so they can develop it

- Add to Design Library

(I will also add this to sebgroup project: https://github.com/orgs/sebgroup/projects/2 so we can follow the progress)

**Comment by ulde01** [comment]
**Status update 2019-01-29** 

- Henrik has made a description and design to this component. 
- Jessi has added it to the Sketch-master, which means that it can be found through Abstract. 
- I have added the component to Design Library. At the moment, you can find it under Components/Upcoming but as soon as it looks and reads ok, I will move it up in the navigation. 
- Henrik also says the component is being developed as we speak, so we will update you once the component code is reusable.

**Comment by JessiNygrenWalhed** [comment]
![stickybars](https://user-images.githubusercontent.com/45595414/51984948-f119aa80-249c-11e9-849d-d43e4c686267.png)
![stickybar_example](https://user-images.githubusercontent.com/45595414/51984962-fa0a7c00-249c-11e9-8289-0f871722e9b5.png)

**Comment by ulde01** [comment]
This component is developed in Angular (yay!). We are working on how to add this so that so others can re-use it.

@hjalmers @splashdust

**Comment by ulde01** [comment]
I updated the
