### ISSUE TITLE
Date-picker

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#21]

**Comment by mzemlickis** [comment]
@ulde01 What are problems with it? I will have a project where there is a need for date picker on the web. 

I found that I have built my own, to suit iPhone 5 needs(width: 288), but its different than the one in the library:
![image](https://user-images.githubusercontent.com/4556944/51455555-d041ae80-1d52-11e9-8fdb-524ec6bbe6c4.png)

**Comment by hjalmers** [comment]
@mzemlickis which library/specs are you referring to, [these](https://designlibrary.sebgroup.com/components/date-picker) on the design library site? If so they're actually based on [this component](https://sebgroup.github.io/bootstrap/datepicker) that's currently available for angular based web apps (works great on iPhone 5 and smaller screens too).

This is how it renders on Iphone 5.
![image](https://user-images.githubusercontent.com/1632755/51471754-28f06600-1daa-11e9-84fb-1cf92c8537b2.png)

I know there's markup available for vanilla as well but no javascript, which you need for this kind of component. When you say that you've built your own, does that include functionality or just the design?

**Comment by mzemlickis** [comment]
@hjalmers buttons at the top are too tiny. Those are 30 height, not 44 as mostly recommended for proper hit area for touch on iOS.

You mentioned smaller screens. What is the smallest support screen that you guys support in general?

**Comment by hjalmers** [comment]
Are you referring to the dropdowns for the month and year @mzemlickis? It's true that apples recommended minimum hit area to used to be 44 pixels, personally I think it's a bit irrelevant to talk about pixles as the actual hit area will vary depending on the pixel ratio of the device rendering the pixels and it's probably why they changed it too. It's more interesting to look at the actual hit area in mm. But of course more pixels will yield a larger hit area in mm too and most of the time bigger is better:)

We could easily adjust the height, the height of the buttons in the calendar inherit their height from normal buttons which currently are 40 pixels. Same goes for the dropdowns too actually, but I see now that the default value of 40 has been overridden, I've opened an issue to fix that https://github.com/sebgroup/bootstrap/issues/82.

Regarding hit area sizes there are tons of good resources on the topic, this are just a few of them:

- [Apple](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/) 44pt (note points not pixels)
- [Optimum button size](https://ux.stackexchange.com/questions/39023/what-is-the-optimum-button-size-of-touch-screen-applications)
- [Microsoft guidelines](https://docs.microsoft.com/en-us/windows/uwp/design/input/guidelines-for-targeting) 48 pixels
- [Touch target sizes](https://www.lukew.com/ff/entry.asp?1085)
- [Android](https://support.google.com/accessibility/android/answer/7101858?hl=en-GB) 48dp (density independent pixel) 

They also link to additional resources on the topic. But to summarise, most sources agree that bigger is better and that the area should be between 7mm to 10mm which is a bit hard to translate in to an actual pixel value. Worth noting is that most interfaces (even mobile) have buttons and other interactive elements with smaller areas than 44 pixels, a lot of elements and buttons on apples own website are actually smaller.

I think a good rule of thumb would be that if it's something that users interact with frequently, it should be bigger. For less used actions it might even be okay to go below 30 pixels (7 mm is less than 30 pixels on some devices too).

I don't mind increasing the default buttons to 44px or maybe even 48px, especially on touch devices, but that means increasing dropdowns, field inputs and a lot of other elements too, and personally I don't think we should focus so much on the actual pixel value as it's a bit deceiving. 

I did some research myself and here's what others are doing with their buttons:
- Github increase from 34px to 39px
- Facebook increase from 32px to 44px (50px like button)
- Apple 38px same size on mobile (pay button)
- Google 36px same size on mobile (google.com)

We also have the option to adjust the size of buttons and texts in our web apps based on the texts size on the device itself, at least on iPhones:) 

I'm also curious if this is a big issue for our users today as we're clearly not worst in class with our default button already being bigger than both apples, fbs, googles and githubs just to mention a few?

All I've heard is that apple said 44px a couple a years ago which actually isn't the case anymore and they're not even abiding to it themselves...

Hehe and finally to answer your question @mzemlickis:) I tend to prefer designing completely fluid layouts, i.e not really specifying width strictly as that's often how you end up breaking responsive layouts. The datepicker won't break but it will start to compress some dates when the width goes below 290 pixels which in reality shouldn't happens as most devices have a minimum width of 320 pixles. Not sure if any smaller exists anymore today to be honest, well I think the old gen apple watch was 272px but it's currently not able to render html anyways:)
