### ISSUE TITLE
Contextual receipt

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#27]
In order to make wizards shorter, and more to the point. Me and Sofia suggest that we add a new component: Contextual receipt.

![image](https://user-images.githubusercontent.com/44571006/51735657-42cec900-2088-11e9-9261-0d49b7d12c0e.png)

After user has completed a wizard, the take-over closes and she is back in the normal view (where she can continue to work un-interupted). But there still needs to be a clear feedback stating that the order/application/process was handled successfully (or not).
This should not be used for flows that require a more formal receipt (i.e. payments, loan applications)

This is sligthly related to Alert-ribbon, but that component should be used to state system status, and not directly linked to a user interaction.

**Comment by SofiaDubbelve** [comment]
I think it is very nice. I need it. Can I have it? One question. Is it always green or can it be purple? Very thank you

**Comment by JessiNygrenWalhed** [comment]
Hey! I say great! (But needs a few visual adjustments, guess this is just a ruff sketch 😍). 
Like @SofiaDubbelve is saying, do we see any needs for other states than green?

**Comment by axelgarciahenriksson** [comment]
"Thank you for completing the wizard we will get back to you in one week when our internal processes has slouched forward"-purple maybe?

**Comment by conandx** [comment]
We in DesignManagementTeam har decided that we need to take an overhaul of all alerts/feedback messages. We do have quite a few versions and a few different needs. On the 11th Jessi and I will have a sit down to try to unify what we should do with all of them to improve the usability for us as designers.

**Comment by conandx** [comment]
Three cases for usage of contextual receipt supplied by @SofiaDubbelve  :)

![kontextuellt kvitto 3](https://user-images.githubusercontent.com/44571006/52336135-638e0b80-2a04-11e9-85f5-7a5cfcda1bda.PNG)
![kontextuellt kvitto1](https://user-images.githubusercontent.com/44571006/52336136-638e0b80-2a04-11e9-8fd4-577c52e14070.PNG)
![kontextuellt kvitto2](https://user-images.githubusercontent.com/44571006/52336138-638e0b80-2a04-11e9-9fe4-6567d58ebeee.PNG)

**Comment by conandx** [comment]
Will be handled as a part of #17 Alerts, and will most likely be either a toast-notification, or be kept as a regular receipt in the wizard.

**Comment by SofiaDubbelve** [comment]
@conandx  I wonder, do the toast notification place itself above other content, or stand alone on a page? and also, do you have any input on how to do it in the pop up above?

**Comment by conandx** [comment]
We need to set the design completely.... but an example of this can be found here: https://sebgroup.github.io/bootstrap/toast-notifications 

They are floating on top of the pages regular content (not separate page)
