### ISSUE TITLE
Describe the building blocks for design

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#29]
We have been talking about a description that goes through the current design concept. The ideas came from the strategic and conceptual work that was done 2015-2017, after the latest redesign. Today we see the result not only in the rebranding, but in "the shell", the digital design principles, the Design Library, etc. We want to describe the thoughts and examples for navigation, login, support, etc so, that we can strive towards it. Easier than guessing!

**Comment by conandx** [comment]
In progress under: https://designlibrary.sebgroup.com/shells/

**Comment by ulde01** [comment]
Am closing the issue as an issue. Ongoing!
