### ISSUE TITLE
Improve structure in Sketch/Abstract

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#3]
(Am learning github slowly... Am testing if the backlog works well here, in "projects" or in "Zenhub")
Thanks for discussing the structure here!

**Comment by conandx** [comment]
Yes please

**Comment by mzemlickis** [comment]
**This is for the upcoming meeting about Splitting the component sketch file.**

Exploring how to split master. First two I made out of semantic UI and 3rd and last is based on our current components file. I think the last one is the best. Enough or segmentation and enough of files to keep abstract syncing at reasonable speeds.

**// Split (1)**

1. Form Elements
- Text inputs
- Text input with icon left
- Text inputs with icon right
- Textboxes (multiple line inputs)
- Buttons

2. Selectors and Dropdowns
- Radio buttons and checkmarks
- Sliders
- Toggles
- Dropdowns
- Calendars and date pickers

3. Navigations, Paginations, Tabs, and Content related elements
- Colorful labels
- Tabs
- Tooltips
- Breadcrumbs
- Notifications
- Paginations
- Progress bars

4. Typography 
- Display
- Headings
- Body
- Caption

5. Colors
- Primary
- Functional (error, success, attention)
- Greys

**// Split (2)**

1. Buttons
2. Text inputs and boxes
3. Sliders
4. Toggles, radio buttons, and checkmarks
5. Dropdowns
6. Calendars and date pickers
7. Tabs
8. Breadcrumbs
9. Progress bars
10. Tooltips, colorful labels (status indicators)
11. Paginations
12. Notifications
13. Typography

**// Split (3)**

1. Accordions
2. Breadcrumbs
3. Bullet point lists
4. Buttons
5. Checkboxes and Radio buttons
6. Colors and tints
7. Datepickers and calendars
8. Densities
9. Dropdowns
10. Icons?!?!?!? Icons guide?!?!?
11. Inline links??!??! Guide?!??!
12. Inputs and textboxes
13. Logotype
14. Modules?!?!
15. Modals (Dialog, foldout, slideout, takeover)
16. Notifications
17. Progress bars
18. Responsive grids?!?!?
19. Expandable sections
20. Segmented controls
21. Side menu
22. Skeleton loader!??! Guide?!?!?
23. Sliders
24. Steppers
25. Toggle switch
26. Tables
27. Tabs
28. Tooltips
29. Topbar
30. Typography
31. Widgets

### // Split (4)

1. Typography
2. Colors
3. Logotypes
4. Responsive Grids / Densities

5. Buttons
6. Inputs, text boxes and tooltips
7. Checkboxes, radio buttons, and toggle switches
8. Sliders and steppers
9. Accordions, expandable sections
10. Dropdowns and date pickers
11. Modals (dialog, foldout, slideout, takeover)
12. Breadcrumbs and tabs
13. Bullet point lists and inline links
14. Tables
15. Tabs and segmented controls
16. Topbar
17. Progress bars, loading and skeletons loaders
18. Notifications
19. Modules and widgets
20. Icons??! Guide??

**Comment by eskolehtme** [comment]
Additional input for structuring basic and more complex elements: http://bradfrost.com/blog/post/atomic-web-design/

**Comment by mzemlickis** [comment]
Split list:

Typography
Colors
Logotypes
Responsive Grids / Densities

Buttons
Inputs, text boxes and tooltips
Checkboxes, radio buttons, and toggle switches
Sliders and steppers
! Accordions, expandable sections
Dropdowns and date pickers
! Modals (dialog, foldout, slideout, takeover)
! Breadcrumbs and tabs
Bullet point lists and (inline links??)
Tables
Tabs and segmented controls
Topbar
Progress bars, loading and skeletons loaders
Notifications
Modules and widgets
Icons??! Guide?? - Esko already have :) You will show how to use FontAwesome
Fifth Element - Esko already have

**Comment by ulde01** [comment]
I just remembered that this issue is also here. Would you like to keep this open? @JessiNygrenWalhed @mzemlickis @eskolehtme

**Comment by ulde01** [comment]
We talked today about the structure in Abstract, that it would help if there was a naming convention of projects:

- We name projects in English
- End name with _country (like project_sw, project_li, etc)
1. Make a list of abbreviations: Jessi and Robert
2. We change our projects asap.
3. Jessi writes an email to the cx-teams

**Comment by ulde01** [comment]
I am closing this issue for now - feel free to re-open it if needed!
