### ISSUE TITLE
Ghost button 

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#35]
**Design change 2019-02-13**

The Ghost button is updated to two versions:

**Ghost button light**
- Transparent with a "White" outline (1 px).
- On hover: Background and outline is "Grey 2".

**Ghost button dark**
- Transparent with a "Grey 2" outline (1 px)
- On hover: Background and outline is "White".

Reason:
The instruction for the Ghost button is clarified. It is used on coloured background and photographs. Ghost light is for darker backgrounds, and Ghost dark for lighter backgrounds. 

![image](https://user-images.githubusercontent.com/45568194/52958043-840a7e00-3393-11e9-9412-0affc3d52d16.png)

Design Library description:
http://designlibrary.sebgroup.com/components/forms/button/#usage

Thank you!
/Ulrika
Design management

See:
* [x]  Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/7
* [x]  Bootstrap https://github.com/sebgroup/bootstrap/issues/95
* [x]  React https://github.sebank.se/DesignLibrary/ReactComponents/issues/45
* [x]  AngularMaterial https://github.sebank.se/DesignLibrary/angular-material-pattern-library/issues/26

**Comment by ulde01** [comment]
![image](https://user-images.githubusercontent.com/45568194/52875006-867e9500-3153-11e9-906d-e9e71ff78eb7.png)

**Comment by SofiaDubbelve** [comment]
![image](https://user-images.githubusercontent.com/46597224/54913140-6bd9d180-4ef2-11e9-99a6-96450ef40ddc.png)
as long as it has nice contrast values :)

**Comment by ulde01** [comment]
I am closing this issue because nothing has happened with it. I assume that it's not relevant or in the wrong repository. No hard feelings! ;) /Ulrika
