### ISSUE TITLE
Grey background (update)

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/design-library#36]
### Design decision 2020-03-23
**Change**
In short, background colour will be White or #F8F8F8

**Details**
https://designlibrary.sebgroup.com/visual-identity/colours/

After many discussions and synk between Design management and Bootstrap. See part of the discussion in this issue.

/Ulrika,
Design management

- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/202
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/282
- [x] Angular https://github.com/sebgroup/ng-components/issues/158
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/98
- [x] React https://github.com/sebgroup/react-components/issues/200
- [x] Delorean https://github.sebank.se/delorean/portfolio-overview/issues/198

### The original issue
During my (Robert) and Panos exploration of the Arena shell last summer we altered the background color from `#f8f8f8` to `#f1f1f1` (darker) and the made the shadow of the cards more crisp, see comparison below.
 
![image](https://user-images.githubusercontent.com/1632755/52998403-861c1d80-3423-11e9-8377-1efb4f5e4a85.png)

![image](https://user-images.githubusercontent.com/1632755/52998505-bc599d00-3423-11e9-8973-43dac6a58ed6.png)

Is this something we should merge back to design library perhaps?

**Comment by conandx** [comment]
We're just looking into adding the "card" to design-library. So far no project have really worked with these very much. We also need so sync to the needs of public web channels that use a white background.
One issue is if items are placed directly on the background the readability may suffer from the darker version. But it contrasts better from the cards.

**Comment by henrikhoglundseb** [comment]
This convo has gone stale. I have made the cards that was suggested in sketch and added it to the abstract lib. We still need to write a description for DL. Might start today. 

The cards looks good and works great with the #f1f1f1 background. Any lighter background will make the contrast not that good. 



Here is an example with the new cards in ADT 


![Forvantat_utfall-desktop-13-feb Copy](https://user-images.githubusercontent.com/46597007/61281061-429ec300-a7b9-11e9-8488-8d1668f78e75.jpg)

**Comment by ulde01** [comment]
### Design decision 2020-03-23:
Background colour":White or F8F8F8
Synk with Design Library and Bootstrap.
