### ISSUE TITLE
Variations of Cancel in modals (text)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#37]
Last week we discussed copy-writing with our copy-colleagues Karin and Gunilla. The topic was all the variations of Cancel in modals that we see in our systems. We agreed on some rules that we want to try to see if they stick:
- The header on the modal and the button text are mirrored
- Avoid posing questions that forces us to use buttons with Yes and No (if possible)
- Avoid writing "Are you sure?"
- Use a Back-button (Tillbaka), not Cancel (Avbryt)
- We also discussed if Delete-button/icon (Ta bort) should be red

Feel free to discuss this and add your own good and less good examples.
/Ulrika

**Comment by ulde01** [comment]
Example of straight-forward text on modal header and buttons 
![image](https://user-images.githubusercontent.com/45568194/53354754-c13cb600-3927-11e9-9fc6-7f7ff46c57ac.png)

**Comment by ulde01** [comment]
Example of "Are you sure?" + Yes... /No...-text on buttons 
![image](https://user-images.githubusercontent.com/45568194/53354834-fb0dbc80-3927-11e9-83c2-df756cda7c66.png)

**Comment by ulde01** [comment]
Exampel of "Are you sure?" and possible confusion on using Back and Cancel on the buttons
![image](https://user-images.githubusercontent.com/45568194/53354914-2a242e00-3928-11e9-96d8-a279189d4d26.png)

**Comment by ulde01** [comment]
Example of "Are you sure" and Continue/Cancel, where asking the question differently, might be clearer.  
![image](https://user-images.githubusercontent.com/45568194/53354985-550e8200-3928-11e9-9a4d-551ece8775bc.png)

**Comment by henrikhoglundseb** [comment]
I agree.

**Comment by ulde01** [comment]
The plan is to talk about this with CX-team on the CX-feedback on Friday March 29th.

**Comment by ulde01** [comment]
Next to do: add to design library.
