### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#38]
### Design review March 27

The accordion has been updated. 

**Change**
- The green “tab border” is removed
- Font in header is 20 px. Subheader is optional: 14 px
- Header cell height: 48 px. If there is also a subheader: 64 px
- Grey hover is added on the header cell
- Content background is still white/none, with the option to make it grey
- Chevron (FontAwesome Light) points up/down (not right/down)
- Guidelines now include: "Use this component mainly for text content"

**Reason**
Many reasons. First of all, it was time to specify the component better. We have adjusted to fit users’ need with more efficient use of space. The direction of chevron is updated to show how it is animated. We also noticed that the component has been (too) content-heavy and added clearer guidelines. 

**Specification**
https://designlibrary.sebgroup.com/components/accordion/

![image](https://user-images.githubusercontent.com/45568194/57231453-cfd7d580-701a-11e9-89af-38ab4e9b15be.png)

**Added to frameworks**
- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/88
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/118
- [x] Angular https://github.com/sebgroup/ng-components/issues/24
- [x] React https://github.com/sebgroup/react-components/issues/15
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/28

Let us know if you have any questions!
/Ulrika
Design management

**Comment by SofiaDubbelve** [comment]
can the new accordion have a nice slide up/down animination? :)

**Comment by henrikhoglundseb** [comment]
definitely! Thats one off the things we will add :)

**Comment by mario-subo** [comment]
I don't think we should limit the amount of content an accordion can hold (in its body at least). It should accept a string of any length and display it as text and possibly even a custom component, meaning whatever you pass in the body will be displayed. This would make the accordion very powerful. This is something, the front x team discussed, the dialog/modal component should be able to do as well.

Also agree it should animate. 

We should also discuss if the logic for the expanded state of the accordion (expanded: true | false) is contained within the component itself or should the parent component manage that (<Accordion expanded={true} />). I would suggest both. An internally managed logic **unless** the expanded flag is explicitly passed down to the component.

**Comment by ulde01** [comment]
Hej @mario-subo , thanks for the input! Good to see you here. We have discussed this at length as well, and user-tested the component. When content = headers, text, inline links, then the component can contain more. But we have seen videos and other huge content which works less well.
