### ISSUE TITLE
Digital signing i new wizard

### ISSUE THREAD

**Issue by SofiaDubbelve** [sebgroup/design-library#46]
![mobileBankID](https://user-images.githubusercontent.com/46597224/54741630-577a9980-4bbf-11e9-92b8-f589a0ea1cdf.PNG)
![Signing with bankID on card](https://user-images.githubusercontent.com/46597224/54741631-58133000-4bbf-11e9-8e21-e2f581213db2.PNG)
![signing woth digipass](https://user-images.githubusercontent.com/46597224/54741632-58133000-4bbf-11e9-8ea9-8668b3fed20e.PNG)

Hello there! I have tried out what digital signing might look like in the wizard with mobile BankID, Digipass and bankID on card. What do you think about it? I also heard that there might be new pictograms... what is the status?

**Comment by SusannaCh** [comment]
![image](https://user-images.githubusercontent.com/45751449/54742362-7bd77580-4bc1-11e9-98ff-3428e1084181.png)

Here is another version we are working with in Alison. Pardon the Swinglish ;). It should of course be swedish or english...

**Comment by henrikhoglundseb** [comment]
This is a view for signing im working on for rådgivningsavtalet for suitability and advisory tool. 

I have the pictograms @olagronlund made if you would like them.

**Comment by SofiaDubbelve** [comment]
@SusannaCh Is it not the case, that the customer has to sign  with the same method as they used when logging in? If so, how come yours can choose?

**Comment by SusannaCh** [comment]
@SofiaDubbelve Good point. I don't know and we have not taken that into consideration.

**Comment by SofiaDubbelve** [comment]
@henrikhoglundseb 

Yes, very thanks! do you know if there is a new design to the grey box as well, or just the new pictogram? any specified sizes to it?
