### ISSUE TITLE
Grid, paddings and margins

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#47]
For both designers and developers:
- If I want to read about grid, paddings and margins, where do I find the info on Design Library?
- How can I use it in my project and know that it's updated according to the lasted design decisions?

**Comment by ulde01** [comment]
**Bootstrap**
If you include Bootstrap, or `type.scss` you get margins for headers. It is set to 0.5 rem (=8px). 

There are also utility classes for margins here: https://getbootstrap.com/docs/4.3/utilities/spacing/

Note the advantage with setting them centrally with rem - you can control the density for an app (sizes, margins, etc) by changing the root size.

**Comment by ulde01** [comment]
**Description in Design library**
Would this be a goo place to add paddings and margins? https://designlibrary.sebgroup.com/components/grid-system/#styles

- Change header to "Grid, paddings and margins"
- Place it under Components or under Patterns

**Comment by axelgarciahenriksson** [comment]
Just a note that many also wonder:
spacing between components 
spacing beween groups of components
etc.
so - basic chunking. At least as a starting point.

**Comment by pmakro** [comment]
Here is a image that shows a summary of what is written in design library
![image](https://user-images.githubusercontent.com/11242625/55776691-dae02a00-5a9d-11e9-89e9-98564fd10c86.png)

Consider the breakpoints as a suggestion, they should depend on the framework chosen (i.e. such as bootstrap).

**Comment by conandx** [comment]
We have recently published his page about grid regarding internetbanks. 
https://designlibrary.sebgroup.com/shells/internet-banks/grid--responsiveness/

But there's probably room for improvement, especially regarding spacing between components.

**Comment by ulde01** [comment]
This issue is constantly current and we try to keep Design Library updated. The different shells have variations of grid, so to understand the latest, read up on the Shell-chapters. If you have any questions, let us know so we can communicate become better. 

New under grid is examples of spacing:
https://designlibrary.sebgroup.com/patterns/grid-and-spacing/

On that note, I am closing this issue for now. 
/Ulrika,
Design Management team
