### ISSUE TITLE
Different ways of saving in the wizard

### ISSUE THREAD

**Issue by SofiaDubbelve** [sebgroup/design-library#49]
![save](https://user-images.githubusercontent.com/46597224/55162373-fd05ae00-5167-11e9-8ece-65aaf031bb91.png)

Hi guys! Me, Susanna and Erik have found 3 different ways of saving in the wizard. Which should it be? Or a fourth option?

**Comment by axelgarciahenriksson** [comment]
What is the difference between “continue later” and “cancel” in these flow? Cancel = I will never see this again? Or cancel for now, do this later. But without saving?

I think the “Save this now, continue later from this point” in the side bar is too hidden. I prefer “Fortsätt senare” in the top (family) example since that is possible to find.

**Comment by SofiaDubbelve** [comment]
I am not sure, but I guess "cancel"=nothig is saved+quit and "Continue later"= save+quit. But I think they could be combined to one button to aviod button-mania and then lead to a pop up, saying that before they leave the wizard, do you want to save or not

**Comment by conandx** [comment]
Hi guys and gals!

In this case we can not be 100% sure about the answer. But we do have a strong belief based on these pictures!

1. We think it's way to much with 4 buttons grouped at the bottom
2. We think it's bad to hide it in the collapsible area to the right. This area will most likely not continue to be collapsible in the future. But it will always be hidden in mobile.
3. We think that this option is an alternative to the close-X, but with saving. So, we believe that the top-right option of placing it in the top-bar is best. We'll update the sketches... as soon as possible!

Reference to: #22

**Comment by SofiaDubbelve** [comment]
Hej

Erik sa att kunderna inte hittade den så bra i högra hörnet. Jag kommer behöva implementera detta inom närmaste veckan så skulle behöva svar snart.

//from Liselott with love

Skickat från min iPhone

3 apr. 2019 kl. 09:57 skrev Conny Andersson <notifications@github.com<mailto:notifications@github.com>>:


Closed #49<https://github.com/sebgroup/design-library/issues/49>.
