### ISSUE TITLE
CRUD-pattern: How do users "Add children"?

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#53]
**Pattern (sep 2019)**
A pattern that describes a uniform way for the user to add both soft and hard properties. This two-step pattern is especially useful in pages where the user has to manually update values.

A white card triggers a slide-out. Use is the same behaviour for all devices.

**Details**
See the measurements (etc) in Design Library:
https://designlibrary.sebgroup.com/patterns/crud/#usage
Design library identifier: component-crud

**Repostories**
- [ ] Vanilla: https://github.com/sebgroup/vanilla-pattern-library/issues/155
- [x] Bootstrap: https://github.com/sebgroup/bootstrap/issues/142
- [ ] Angular: https://github.com/sebgroup/ng-components/issues/44
- [x] AngularMaterial: https://github.com/sebgroup/seb-angular-material/issues/75
- [ ] React: https://github.com/sebgroup/react-components/issues/51

Any questions or feedback? /Ulrika designlibrary@seb.se

**Comment by SusannaCh** [comment]
![add lenght](https://user-images.githubusercontent.com/45751449/55472336-2745e880-560c-11e9-8dea-2a1dcc7cc468.gif)

 Here is one idea for "adding" another value (the ocr lenght). Concept idea. MIght not be exactly what you mean... :)

**Comment by henrikhoglundseb** [comment]
![Screenshot 2019-04-15 at 14 32 26](https://user-images.githubusercontent.com/46597007/56132903-83552900-5f8b-11e9-8a0c-ea70e345d932.png)

![Screenshot 2019-04-15 at 14 33 24](https://user-images.githubusercontent.com/46597007/56132910-86e8b000-5f8b-11e9-86a2-659a544bde33.png)
Dectop



![3-har-du-några-barn-slideOut](https://user-images.githubusercontent.com/46597007/56132970-a253bb00-5f8b-11e9-8623-89cc939b7edf.png)
![3-har-du-några-barn-1](https://user-images.githubusercontent.com/46597007/56132971-a253bb00-5f8b-11e9-8d27-1a3dce93cc70.png)
Mobile


Create, read, update, delete

**Comment by ulde01** [comment]
This could be a pattern in Design library.

**Comment by ulde01** [comment]
Add a "CRUD-pattern" with examples. @henrikhoglundseb

**Comment by ulde01** [comment]
This is now a pattern on Design library.
@henrikhoglundseb Is this developed? Can the team make a resuable component and add it?

https://designlibrary.sebgroup.com/patterns/crud/
