### ISSUE TITLE
Synk the list component desktop and mobile

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#58]

**Comment by henrikhoglundseb** [comment]
https://designlibrary.sebgroup.com/components/list/#styles 

This is how list looks. I and @JessiNygrenWalhed will create mobile version and add context

**Comment by JessiNygrenWalhed** [comment]
https://designlibrary.sebgroup.com/components/list-components/list/
(a better link... look omn the styles tab).

So we are talking about these lists. In Design Library the "list" component also includes "list groups" -  bullet lists,  numbered lists and lists with checkmarks. Could it be an idea to make the list in my example a different component? Seems to me they are really two different things. This list is, as the description i DL says "-The simplest way of listing data in an orderly fashion with labels and associated data. Lists are used when the added functionality of tables are not required."

What it is supposed to be called?! I have no idea. It is related to a table right? 

We are exploring the layout on the list as well as the font sizes on label and value. Desktop should for example have a max width when using left/right set label and value. When over the max width it should look something like example 2. But how about the fons sizes? 14/16, 16/16? Optional?

"When there is sufficient space, data is listed to the right of the label, but in smaller containers, such as a slide-out, it may be displayed the same was as done in a mobile device with the label above the data." Just as today for mobile! Only some adjustments on text sizes. Se examples list_example_3, _4, _5, & _6. 

Give me your thoughts! 
/Jessi

![list_example_1](https://user-images.githubusercontent.com/45595414/58098986-01d06680-7bdb-11e9-99a5-ef3acbd690ba.png)
![list_example_2](https://user-images.githubusercontent.com/45595414/58098991-04cb5700-7bdb-11e9-8447-0e82932616e3.png)
![list_example_3](https://user-images.githubusercontent.com/45595414/58099311-a94d9900-7bdb-11e9-8cf0-8019d316e526.png)
![list_example_4](https://user-images.githubusercontent.com/45595414/58099322-ad79b680-7bdb-11e9-8a1e-34d669a23fd8.png)
![list_example_5](https://user-images.githubusercontent.com/45595414/58099325-b074a700-7bdb-11e9-9d7d-8bba06892f54.png)
![list_example_6](https://user-images.githubusercontent.com/45595414/58099334-b4a0c480-7bdb-11e9-9a0d-547cd0a15bef.png)
