### ISSUE TITLE
upload file 

### ISSUE THREAD

**Issue by SofiaDubbelve** [sebgroup/design-library#61]
![Capture](https://user-images.githubusercontent.com/46597224/58164072-6a741d80-7c85-11e9-8a36-6bdf255d6ed3.PNG)
![Skärmavbild 2019-05-22 kl  11 27 13](https://user-images.githubusercontent.com/46597224/58164077-6ba54a80-7c85-11e9-9522-265f73f0af31.png)

Hi! Here are two quick examples on how to design the upload file-functionality. One by me and one by Malin :) How would YOU like it?

**Comment by henrikhoglundseb** [comment]
It sounds like a good idea. Continue With the design and create a prototype with all states and options. 

The button should be the secondary button and not on two lines. Try to combine it with the standard "attached files".

**Comment by conandx** [comment]
Gillar denna ikonen bättre (https://fontawesome.com/icons/cloud-upload?style=light )
![image](https://user-images.githubusercontent.com/44571006/58869238-2427b100-86be-11e9-8745-98b5ebd60808.png)

**Comment by JessiNygrenWalhed** [comment]
Could this be a visual take on it? 
The Drag & drop area should stand by its own, the other option to upload file by browsing should be outside that box. Malin had red times-icon on her uploaded documents. Stands out a bit too much i think. The times-icon tells the user what happens. @henrikhoglundseb What is the standard "attatched files"?

Do you think the drop area is to small? 
@SofiaDubbelve Vad tycker du? 
![drag_drop _jessi](https://user-images.githubusercontent.com/45595414/58869614-d8293c00-86be-11e9-8902-e7fa4d6e972f.png)

**Comment by SofiaDubbelve** [comment]
Hi! I like the larger drop area and that you put the option of uploaing file beside it instead of under :) however I think I will continue with blue border since it looks a little bit more "awake" and interactable (if that is a new word I totally take all credit) and I will use the design library pictogram in my images for uploading file, because the one with the cloud I percieve a bit more of "upload to cloud" but maybe that´s just me
but thanks for the engagement, i will post the end result soon!

**Comment by SofiaDubbelve** [comment]
allright  a new iteration :) https://8s6fmt.axshare.com/#g=1&p=drag_and_drop__1_

**Comment by JessiNygrenWalhed** [comment]
> Hi! I like the larger drop area and that you put the option of uploaing file beside it instead of under :) however I think I will continue with blue border since it looks a little bit more "awake" and interactable (if that is a new word I totally take all credit) and I will use the design library pictogram in my images for uploading file, because the one with the cloud I percieve a bit more of "upload to cloud" but maybe that´s just me
> but thanks for the engagement, i will post the end result soon!

Sofia, I think this is something that we need to discuss further, so we design a component that we can use, that looks and acts the same across all our platforms. The pictogram should not be used as small as I think looks the best here. But the Icon can of course be discussed also! So please make a new suggestion and we talk again. BEFORE the end result! 
/Jes.

**Comment by JessiNygrenWalhed** [comment]
> allright a new iteration :) https://8s6fmt.axshare.com/#g=1&p=drag_and_drop__1_

The blue drop area looks the same as the button. But it is not clickable. I suggest you make it as in my sketch.

**Comment by conandx** [comment]
There's also an implementation to consider.... its bootstrap and holds 2 versions.
![image](https://user-images.githubusercontent.com/44571006/60500657-00568b80-9cbb-11e9-8a09-6d93455d2b40.png)

**Comment by conandx** [comment]
I think we should use the examples from @SofiaDubbelve   Perhaps she can add some screen-shots from the real built solution too?

**Comment by SofiaDubbelve** [comment]
![state1](https://user-images.githubusercontent.com/46597224/71175699-77331100-2268-11ea-9c33-e90949185e20.PNG)
![state2](https://user-images.githubusercontent.com/46597224/71175701-77cba780-2268-11ea-8115-b4ab8bfa481f.png)
![state3](https://user-images.githubusercontent.com/46597224/71175700-77331100-2268-11ea-8d79-802363ffedbb.png)

here is what we have done! the feedback is displayed for 3 seconds, then it goes back to default

**Comment by ghost** [comment]
In Malins project "Säkra meddelanden" we let the entire page be the drop zone. (At least that was what we decided. Not sure that was what came out. 
Malin maybe have some screenshots to share from the actual solution? 
(My example just quickly sketched out on Sofias project "Leasing".
![Drag   drop](https://user-images.githubusercontent.com/45595414/71182071-b320a300-2275-11ea-9bf3-8e15e70b2bff.png)
![Drag   drop_dropzone](https://user-images.githubusercontent.com/45595414/71182081-b74cc080-2275-11ea-8f22-da98f9216e63.png)


/Jes.

**Comment by henrikhoglundseb** [comment]
@SofiaDubbelve The developed drag and drop looks good. Looking forward to take part of the insights from the user :) GREAT WORK

**Comment by ulde01** [comment]
This feature is now described in Design Library: 
https://designlibrary.sebgroup.com/patterns/drag-and-drop/

I am closing this issue without adding this to be developed as a common component (yet), as it is not a common component. Feel free to use it as described. If you have feedback on the design, please let us know! We are always looking to improve.

/Ulrika,
Design management team
