### ISSUE TITLE
FontAwsome icons- change to regular

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#65]
**Bootstrap-sync, July 2019**
Most of the icons used in fontawsome are too light in the light-version.
We should change to regular to make them work in the small sizes.

- [x] update DL description, news, change log.
- [x] update vanilla; https://github.com/sebgroup/vanilla-pattern-library/issues/151 
- [x] update bootstrap examples
- [x] update FA-instructions in github

**Comment by hjalmers** [comment]
@ulde01 when do you think this will updated in DL? I've updated the instructions in github and all the examples in bootstrap and was planning on sending an email to all teams who have taken a license seat just to inform them on the change from light to regular and point out the right way to implement the icons as we aren't allowed to load the library from an external cdn which a lot of teams are doing right now...

**Comment by ulde01** [comment]
I don't see a reason why we should wait :)
Can you include me in your e-mail? Maybe I can reuse some from it to the DL news, change log and description update. Thanks!

**Comment by ulde01** [comment]
Done! Your turn! ;) @hjalmers
