### ISSUE TITLE
Grey colour synk between SEB design and our frameworks

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#67]
### Design decision 2020-03-23
 
**What is this**
Grey shade synk with Design Management and Bootstrap (Robert Hjalmers)

**Change**
- Design Library will use the same naming convention as SEB Bootstrap (from "grey 8" to "grey 800")
- Design Library will change colours 1-7 and use same grey shades as SEB Bootstrap
- Bootstrap will change the two darker colours 800 and 900 (800: from #343434 to #333333, 900: from #212121 to #1A1A1A)

**Correct grey shades**
$white:    #fff !default;
$gray-100: #f8f8f8 !default;
$gray-200: #e9e9e9 !default;
$gray-300: #dedede !default;
$gray-400: #cecece !default;
$gray-500: #adadad !default;
$gray-600: #868686 !default;
$gray-700: #494949 !default;
$gray-800: #333333 !default;
$gray-900: #1A1A1A !default;
$black:    #000 !default; 

**Reason**
Our designers and developers must have the same colour references. The original reason was that the disabled colours sometimes blended in with the background. Then it was noted that colours were out of synk.

- [x] Sketch - Henrik
- [x] Design Library (colour page, all pages, change log, news, Slack) - Ulrika
- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/198
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/274

**Comment by henrikhoglundseb** [comment]
The colors hasen't changed in bootstrap and design lib. 

Should DL follow Bootstrap?

Should the naming be grey-100 for lightest grey also in DL, in DL right now grey-1 is the darkest.

Are the correct colors the one that is in bootstrap. 

@ulde01 @hjalmers @JessiNygrenWalhed @conandx 

https://github.com/sebgroup/bootstrap/blob/master/scss/_variables.scss

**Comment by ulde01** [comment]
The answer is yes, DL will change the names of grey colours to be in the same naming order as BS.  Will will also change change one of the greys to improve the constrast. @henrikhoglundseb knows the details.

**Comment by henrikhoglundseb** [comment]
The naming in our **Design lib** will be changed/arranged to match SEB bootstrap. Grey-9 will become Grey-1, Grey-8 will become grey-2 and so on. 

The adjustments in **SEB Bootstrap** will be.

$gray-800: #343434 -----------> $gray-800: #333333
$gray-900: #212121 ------------> $gray-900: #1A1A1A

**Comment by ulde01** [comment]
These are the grey colours used in Design Library:

![image](https://user-images.githubusercontent.com/45568194/74739183-9e9e5e00-5258-11ea-9e65-7380b11f9d39.png)

Change:
- The order of colours have switched to be in synk with SEB Bootstrap
- Two shades have been updated: 
-- Grey 8: from #343434 to #333333
-- Grey 9: from #212121 to #1A1A1A

**Comment by hjalmers** [comment]
Current values that should be used today: 2020-03-23 :smiley:

**Gray scale**
```scss
$white:    #fff !default;
$gray-100: #f8f8f8 !default;
$gray-200: #e9e9e9 !default;
$gray-300: #dedede !default;
$gray-400: #cecece !default;
$gray-500: #adadad !default;
$gray-600: #868686 !default;
$gray-700: #494949 !default;
$gray-800: #333333 !default;
$gray-900: #1A1A1A !default;
$black:    #000 !default;
```

**Background color:** `#f8f8f8`
**Text color:** `#333333` (body and headers)

**Comment by ulde01** [comment]
![image](https://user-images.githubusercontent.com/45568194/77457126-88a62f00-6dfc-11ea-9405-86165416f726.png)

**Comment by ulde01** [comment]
We also decided that a few things need to stand alone, and be separated from the other colours:
- "Background colour" (varies today, but will be F8F8F8 - I will create another issue for this) 
- "Link colour" (no change: Dark blue 2 #007AC7)
- "Text colour" (no change: Grey 800 #333333)
