### ISSUE TITLE
Disabled or not? (discussion)

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#78]
We are currently discussing how to treat disabled buttons/components/services and empty states. What is the best way to guide the user through their journey?
 
- Should we present the minimum amount of components? Or show everything and disable what they don't need.
- Should a CTA-button be disabled until the user has made all the relative selections? Or should the user be able to click on the button in order to get feedback?

There are accessibility factors to consider, as well as trends in the usability world. Now we want your opinion. What are the use cases you work on? The exceptions? GO!

**Comment by Jolidstrom** [comment]
In regards to disabled buttons: I think avoid them! :) Here is a great article explaining why disabled buttons are bad: https://axesslab.com/disabled-buttons-suck/ 

//Jonatan

**Comment by SofiaDubbelve** [comment]
I agree that disable buttons are something to avoid, and especially in forms. If I accidently forget to answer a question, the best solution I think is to let me click either way, and then use anchor link to the error message (if it regards a forgotten question in the form), instead of having a disabled button. I won´t know why it is disabled. 

if the case does not involve a form, I would maybe try if a toast notification or pop up or some similar alert (that not only says something is wrong - but also how I fix it) could do the trick

**TLDR**
Let user click button - give feedback they need do something

**Comment by ghost** [comment]
I agree with you @SofiaDubbelve  & @Jolidstrom ! There are a lot of good reasons not to use the disabled button like we do now! Read the article that @Jolidstrom posted above 👆🏼

**A few excerpts from the article:**
"It is a bad practice to disable buttons. Disabling the button prevents our chance to tell the user what is wrong. The user keeps clicking the button and is totally in the dark why nothing happens. Keep the button enabled. Let the user click the button. Then show the message why it can’t proceed."

"If you really, really want to indicate that a button is disabled, do some css magic and make it look a bit grey (but with sufficient contrasts). And then turn it green or blue when everything is filled in correctly. But keep the button enabled in the code at all times and put focus on an error message if it’s clicked and there’s something wrong"

**"So disabled buttons exclude users with disabilities. It’s one of the best reasons to stop using them."**

/Jessi

**Comment by ulde01** [comment]
Am adding another comment for the log:

"Jag föredrar knappen är aktiv och när jag klickar på den så får jag feedback om vad jag ska göra. Om jag trycker på den för tidigt vill jag få tydlig info om vilka fält jag har missat. Att jag ”scrollas” dit och det finns en markering och en förklarande text. Jag vill helst inte att knappen är disabled och absolut inte att knappen inte ens syns (=utbytt mot en text)"

**Comment by ulde01** [comment]
Am adding another comment for the log:

"Jag föredrar att knppen för att gå vidare är disabled. Fast inte disabled på riktigt. Den ser visuellt ut som att den är disabled, men den är klickbar - och resultat vid klick är att användaren får se en förklaring till varför den är disabled.

Kombinerat med:
https://www.nngroup.com/articles/errors-forms-design-guidelines/

Men i den artikeln, punkt 8: **Validation summaries**: 
Inte validation summaries i toppen av inmatningen, utan vid knappen. 
Se enkla lånet-ansökan på seb.se som exempel på dåligt - när man gjort färdigt allt får man info om att något är på tok - men det ser man inte, speciellt mobilt. Informationen måste vara vid knappen. 
Som i punkt 3 i artikeln. Keep Error Messages next to Fields. 

Att knappen är aktiv och att jag får feedback när jag klickar på den, är också bra när vi visar upp produktval och dylikt som del av ett flöde. I P&F fick vi feedback att det är viktigt att förstå vad det finns för erbjudande som INTE rekommenderas på grund av ens svar. Detta såklart enbart om det är få möjliga alternativ, inte 200 aktiefonder. 

Det är dock möjligt att P&F är ett särfall. Jag försöker själv sätta mig in i hur det skulle vara att få råd kring val av bil/dator/semestermål. Man kanske bara vill veta vad som passar mig bäst. Om man inte är managerial kontrollbehov etc, som man är när man ska köpa tjänstepension till sina anställda."

**Comment by freddesmail** [comment]
I also agree that disabled buttons should be avoided. Instead, let the user click the button so we can tell them what is wrong and what to do about it. If it is a form, this is my suggestion on how to handle it:

1.  Place  error message close to the invalid field.
2. For accessibility reasons, link the invalid field to the error message using attributes `aria-describedby` and `aria-invalid="true"` . By doing this, a screenreader will read the error text when the field has focus. 
3. Set focus on the first invalid field in the form. Now the user can see (or hear if using screenreader) the invalid field and the error message.

**Comment by malinbergman** [comment]
I agree with @SofiaDubbelve - Let user click button - give feedback they need do something!

**Comment by axelgarciahenriksson** [comment]
I remember testing ticket vending machines with a fully digital touch screen gui. Nothing was visually disabled and customers were desperately pounding on the ‘next step’ button without understanding why they couldn’t continue. They didn’t see the error message telling them to choose between the options above. The solution was to disable/hide everything that was not meant to be immediately interacted with - and then enable it. 

So when it comes to forms/choose between stuff/things that need to be done in a certain order - it might be a good idea to disable. Or even hide. 

Some sites have even gone so far that they hide the password field, without showing it until you have entered the user id/name/email. That is a bit extreme in my view. 

And the downside to this is of course that one doesn’t have a clue how long it will take to go through the form. In that perspective, I like our Enkla Lånet application where I can flip through the form and know what is expected of me before starting. Whether one appreciate one or the other probably depends on personality and situation. 

On the other hand, for the examples in Jonatan’s Article, like Facebook and google analytics, it would be horrible to hide options - one want to see what is possible to do or choose between. However, it would be super irritating to not know what I am allowed to do or not - to have a lot of options that look like I can use them, but just get ‘No you cannot’ messages! Please tell me in advance. 

So I think all options are bad - and good. I’m happy that smarter brains will decide this.

**Comment by SofiaDubbelve** [comment]
I think there is a very valid point in the fact that the error message has to be very clear, so the user finds it if they click on a non-disabled-button! otherwise the whole concept falls

**Comment by ulde01** [comment]
Thank you for the discussion! I will close it for now. /Ulrika
