### ISSUE TITLE
Responsive table - Cell table

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#89]
### What is needed?
The component needs both
- design
- descriptions
- examples

Here are instructions to help you: https://github.com/sebgroup/design-library/issues/95

DMT, use comments below to describe what we know/think so far.

/Ulrika

**Comment by ulde01** [comment]
This component is developed (delorean) and needs descriptions and images. It is a variation of table so check out how to incorporate the description in: https://designlibrary.sebgroup.com/components/table/

The great thing about this is what happens to the table when it is displayed in a smaller viewport. So when is it perfect to use? And when is it not?

**Comment by conandx** [comment]
- Give examples of our **3 ways** of doing responsive tables and when to choose what. (prioritised columns / scrolling table / cell table )
- **Prioritised columnns**: simples choise: choose which columns should be hidden in smaller viewports.
- **Scrolling table**: the table size is fixed and user may scroll in horizontaly to view all columns.
- **Cell table**: all or prioritized columns are grouped into one cell that may be spread on multiple lines to summarize the columns of the table.

**Comment by ulde01** [comment]
I added this to the table page - THANK YOU! @conandx
