### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#90]
### Design update 2020-01-13

**What is this?**
This component calls attention to a status/tag/category.
![image](https://user-images.githubusercontent.com/45568194/72283689-95114d00-363f-11ea-952d-556b86833a3e.png)

**Details**
See the specification to get all the right details:
https://designlibrary.sebgroup.com/components/badge/

**Component identifier**
component-badge

**Follow up on development:**
- [x] Vanilla https://github.com/sebgroup/vanilla-pattern-library/issues/173
- [x] Bootstrap https://github.com/sebgroup/bootstrap/issues/200
- [x] Angular https://github.com/sebgroup/ng-components/issues/73
- [x] AngularMaterial https://github.com/sebgroup/seb-angular-material/issues/87
- [x] React https://github.com/sebgroup/react-components/issues/103

Thank you!
/Ulrika

**Comment by yousifalraheem** [comment]
I don't think this component needs a React or Angular component since it's not interactive. You can easily render this using
```html
<span class="badge badge-danger"></span>
```
If there is a design change, then it should just be implemented in **@sebgroup/bootstrap**.

**Comment by ulde01** [comment]
Great input! I add these changes to all our repos just in case it matters to you. It's difficult for me to judge so I am hoping that you close all design issues (with this type of comment) when they are not relevant. Thank you!
