### ISSUE TITLE
Wizard - light

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#91]
### What is needed?
The component needs both
- design
- descriptions
- examples

Here are instructions to help you: https://github.com/sebgroup/design-library/issues/95

DMT, use comments below to describe what we know/think so far.

/Ulrika

**Comment by ulde01** [comment]
Rename the CRUD-component and give it more examples and description?

**Comment by conandx** [comment]
- I don't think CRUD is confined to only be in a wizard...
- Added details for more complex version in Fondhandel - starta sparande (card added to group information.

**Comment by ulde01** [comment]
When you need a full-on, stay-focused flow - use the wizard
When you want a lighter 1-2-3 guide - use signals like the progress indicator
![image](https://user-images.githubusercontent.com/45568194/93624523-c7e6be80-f9e0-11ea-94f6-4ea45f6cd575.png)
