### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#92]
### What is needed?
The component needs both
- design
- descriptions
- examples

Here are instructions to help you: https://github.com/sebgroup/design-library/issues/95

DMT, use comments below to describe what we know/think so far.

/Ulrika

**Comment by ulde01** [comment]
The design of widgets have been evolved and the descriptions and images need to be updated.

**Comment by conandx** [comment]
- probably the most correct sketches are from Panos in the Arena-project... IBP is not ready for widgets yet

**Comment by ulde01** [comment]
Widgets have been updated with Panos specification and examples. We will add guidelines as Arena progresses. I am closing this issue for now but it can be revisited when needed.
