### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by conandx** [sebgroup/design-library#94]
### What is needed?
The component needs both
- design
- descriptions
- examples

Here are instructions to help you: https://github.com/sebgroup/design-library/issues/95

DMT, use comments below to describe what we know/think so far.

/Ulrika

**Comment by conandx** [comment]
- Very small Atom
- when/how to use.... flexible :)
- related to background-colour?
- Arena-style or something evolved? Related to hybrid-ideas?

**Comment by ulde01** [comment]
Panos has made a specification for the Card container - thank you! We will add guidelines (when and how to use, relation to background, etc) as Arena progresses. I am closing this issue for now but it can be revisited when needed.
