### ISSUE TITLE
Progress indicatior

### ISSUE THREAD

**Issue by ulde01** [sebgroup/design-library#97]
Is this ready to be lifted, Henke?
https://designlibrary.sebgroup.com/components/upcoming/progress-indicator/

Do you want to add anything?

**Comment by conandx** [comment]
We've learned that step 1 should not be green until you are on step2. if not, step 3/3 is full green, but the user is not yet done with the flow.
perhaps there's a need to add one more colour? darker grey?

**Comment by ulde01** [comment]
This component is designed and finished. You can find the description among components in Design Library. /U
