### ISSUE TITLE
Hybridcomponent - Close X 

### ISSUE THREAD

**Issue by henrikhoglundseb** [sebgroup/design-library#98]
In the hybridwork do i suggest a alternative to the closing X that we have today. Its basically the same component but with a geay circle around it to enhance the feeling of the hit area. The X is black in this version, and that feels great. 

This is how the X looks in the native app and i think it will work great in all devices. 

![IMG_B62DDDE340AB-1](https://user-images.githubusercontent.com/46597007/71250306-a0fb3f00-231f-11ea-9c62-3e8f4628d58a.jpeg)

<img width="371" alt="Screenshot 2019-12-20 at 11 49 41" src="https://user-images.githubusercontent.com/46597007/71250341-b83a2c80-231f-11ea-9a7c-b64734e43753.png">

**Comment by conandx** [comment]
We always want the close-X to be round in mobile. For desktop we want the round circle to be used as hover-effect.

**Comment by henrikhoglundseb** [comment]
:D
