### ISSUE TITLE
Change / decide color of Close X 

### ISSUE THREAD

**Issue by henrikhoglundseb** [sebgroup/design-library#99]
Right now do we mix between black #333333 and dark-blue-1 I purpose that we decide it should be #333333. What do you think ? 

<img width="460" alt="Screenshot 2019-12-20 at 11 58 21" src="https://user-images.githubusercontent.com/46597007/71250487-12d38880-2320-11ea-9ad3-c48dd02349d0.png">
<img width="525" alt="Screenshot 2019-12-20 at 11 58 31" src="https://user-images.githubusercontent.com/46597007/71250488-12d38880-2320-11ea-9536-2a087ca6ad4e.png">

**Comment by conandx** [comment]
And related to this - making the header area larger (more padding) and the x-symbol thinner.

**Comment by conandx** [comment]
Just going to check the last details of glyph, colour and size.

**Comment by conandx** [comment]
And.... perhaps the mobile version of this close should be the new mobile version created in #98
